// @generated by protoc-gen-es v1.1.0
// @generated from file asset/v1/asset.proto (package asset.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * METADATA 
 *
 * @generated from message asset.v1.Asset
 */
export const Asset = proto3.makeMessageType(
  "asset.v1.Asset",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "external_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "attributes", kind: "message", T: Asset_Attribute, repeated: true },
    { no: 6, name: "co2e", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "footprint" },
    { no: 7, name: "co2o", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "footprint" },
    { no: 8, name: "gallery", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 9, name: "video", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "created_at", kind: "message", T: Timestamp },
    { no: 11, name: "updated_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message asset.v1.Asset.Attribute
 */
export const Asset_Attribute = proto3.makeMessageType(
  "asset.v1.Asset.Attribute",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "Asset_Attribute"},
);

