// @generated by protoc-gen-es v1.1.0
// @generated from file wallet/v1/wallet.proto (package wallet.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Transaction } from "../../transaction/v1/transaction_pb.js";

/**
 * @generated from message wallet.v1.GetAddressResponse
 */
export const GetAddressResponse = proto3.makeMessageType(
  "wallet.v1.GetAddressResponse",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.GetMetadataRequest
 */
export const GetMetadataRequest = proto3.makeMessageType(
  "wallet.v1.GetMetadataRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.GetSignatureRequest
 */
export const GetSignatureRequest = proto3.makeMessageType(
  "wallet.v1.GetSignatureRequest",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.GetSignatureResponse
 */
export const GetSignatureResponse = proto3.makeMessageType(
  "wallet.v1.GetSignatureResponse",
  () => [
    { no: 1, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.SendTransactionRequest
 */
export const SendTransactionRequest = proto3.makeMessageType(
  "wallet.v1.SendTransactionRequest",
  () => [
    { no: 1, name: "transaction", kind: "message", T: Transaction },
    { no: 2, name: "authorizations", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message wallet.v1.SendTransactionResponse
 */
export const SendTransactionResponse = proto3.makeMessageType(
  "wallet.v1.SendTransactionResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

