// @generated by protoc-gen-es v1.0.0
// @generated from file wallet/v1/wallet.proto (package wallet.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message wallet.v1.GetAddressResponse
 */
export declare class GetAddressResponse extends Message<GetAddressResponse> {
  /**
   * @generated from field: optional string address = 1;
   */
  address?: string;

  constructor(data?: PartialMessage<GetAddressResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.GetAddressResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAddressResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAddressResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAddressResponse;

  static equals(a: GetAddressResponse | PlainMessage<GetAddressResponse> | undefined, b: GetAddressResponse | PlainMessage<GetAddressResponse> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.CreateSignatureRequest
 */
export declare class CreateSignatureRequest extends Message<CreateSignatureRequest> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  constructor(data?: PartialMessage<CreateSignatureRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.CreateSignatureRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSignatureRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSignatureRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSignatureRequest;

  static equals(a: CreateSignatureRequest | PlainMessage<CreateSignatureRequest> | undefined, b: CreateSignatureRequest | PlainMessage<CreateSignatureRequest> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.CreateSignatureResponse
 */
export declare class CreateSignatureResponse extends Message<CreateSignatureResponse> {
  /**
   * @generated from field: string signature = 1;
   */
  signature: string;

  constructor(data?: PartialMessage<CreateSignatureResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.CreateSignatureResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateSignatureResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateSignatureResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateSignatureResponse;

  static equals(a: CreateSignatureResponse | PlainMessage<CreateSignatureResponse> | undefined, b: CreateSignatureResponse | PlainMessage<CreateSignatureResponse> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.CreateTransactionRequest
 */
export declare class CreateTransactionRequest extends Message<CreateTransactionRequest> {
  /**
   * @generated from field: string transfer = 1;
   */
  transfer: string;

  constructor(data?: PartialMessage<CreateTransactionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.CreateTransactionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTransactionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTransactionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTransactionRequest;

  static equals(a: CreateTransactionRequest | PlainMessage<CreateTransactionRequest> | undefined, b: CreateTransactionRequest | PlainMessage<CreateTransactionRequest> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.CreateTransactionResponse
 */
export declare class CreateTransactionResponse extends Message<CreateTransactionResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  constructor(data?: PartialMessage<CreateTransactionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.CreateTransactionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTransactionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTransactionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTransactionResponse;

  static equals(a: CreateTransactionResponse | PlainMessage<CreateTransactionResponse> | undefined, b: CreateTransactionResponse | PlainMessage<CreateTransactionResponse> | undefined): boolean;
}

