// @generated by protoc-gen-es v1.0.0
// @generated from file wallet/v1/wallet.proto (package wallet.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Transaction } from "../../transaction/v1/transaction_pb.js";

/**
 * @generated from message wallet.v1.GetAddressRequest
 */
export declare class GetAddressRequest extends Message<GetAddressRequest> {
  constructor(data?: PartialMessage<GetAddressRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.GetAddressRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAddressRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAddressRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAddressRequest;

  static equals(a: GetAddressRequest | PlainMessage<GetAddressRequest> | undefined, b: GetAddressRequest | PlainMessage<GetAddressRequest> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.GetAddressResponse
 */
export declare class GetAddressResponse extends Message<GetAddressResponse> {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  constructor(data?: PartialMessage<GetAddressResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.GetAddressResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAddressResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAddressResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAddressResponse;

  static equals(a: GetAddressResponse | PlainMessage<GetAddressResponse> | undefined, b: GetAddressResponse | PlainMessage<GetAddressResponse> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.SignTransactionRequest
 */
export declare class SignTransactionRequest extends Message<SignTransactionRequest> {
  /**
   * @generated from field: transaction.v1.Transaction transaction = 1;
   */
  transaction?: Transaction;

  constructor(data?: PartialMessage<SignTransactionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.SignTransactionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignTransactionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignTransactionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignTransactionRequest;

  static equals(a: SignTransactionRequest | PlainMessage<SignTransactionRequest> | undefined, b: SignTransactionRequest | PlainMessage<SignTransactionRequest> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.SignTransactionResponse
 */
export declare class SignTransactionResponse extends Message<SignTransactionResponse> {
  /**
   * @generated from field: string signature = 1;
   */
  signature: string;

  constructor(data?: PartialMessage<SignTransactionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.SignTransactionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SignTransactionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SignTransactionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SignTransactionResponse;

  static equals(a: SignTransactionResponse | PlainMessage<SignTransactionResponse> | undefined, b: SignTransactionResponse | PlainMessage<SignTransactionResponse> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.PushTransactionRequest
 */
export declare class PushTransactionRequest extends Message<PushTransactionRequest> {
  /**
   * @generated from field: transaction.v1.Transaction transaction = 1;
   */
  transaction?: Transaction;

  /**
   * @generated from field: repeated string authorizations = 2;
   */
  authorizations: string[];

  constructor(data?: PartialMessage<PushTransactionRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.PushTransactionRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushTransactionRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushTransactionRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushTransactionRequest;

  static equals(a: PushTransactionRequest | PlainMessage<PushTransactionRequest> | undefined, b: PushTransactionRequest | PlainMessage<PushTransactionRequest> | undefined): boolean;
}

/**
 * @generated from message wallet.v1.PushTransactionResponse
 */
export declare class PushTransactionResponse extends Message<PushTransactionResponse> {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  constructor(data?: PartialMessage<PushTransactionResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "wallet.v1.PushTransactionResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushTransactionResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushTransactionResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushTransactionResponse;

  static equals(a: PushTransactionResponse | PlainMessage<PushTransactionResponse> | undefined, b: PushTransactionResponse | PlainMessage<PushTransactionResponse> | undefined): boolean;
}

