// @generated by protoc-gen-es v1.0.0
// @generated from file wallet/v1/wallet.proto (package wallet.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message wallet.v1.GetAddressResponse
 */
export const GetAddressResponse = proto3.makeMessageType(
  "wallet.v1.GetAddressResponse",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message wallet.v1.CreateSignatureRequest
 */
export const CreateSignatureRequest = proto3.makeMessageType(
  "wallet.v1.CreateSignatureRequest",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.CreateSignatureResponse
 */
export const CreateSignatureResponse = proto3.makeMessageType(
  "wallet.v1.CreateSignatureResponse",
  () => [
    { no: 1, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.CreateTransactionRequest
 */
export const CreateTransactionRequest = proto3.makeMessageType(
  "wallet.v1.CreateTransactionRequest",
  () => [
    { no: 1, name: "transfer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message wallet.v1.CreateTransactionResponse
 */
export const CreateTransactionResponse = proto3.makeMessageType(
  "wallet.v1.CreateTransactionResponse",
  () => [
    { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

