// @generated by protoc-gen-es v1.1.0
// @generated from file certificate/v1/certificate.proto (package certificate.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * METADATA 
 *
 * @generated from message certificate.v1.Certificate
 */
export const Certificate = proto3.makeMessageType(
  "certificate.v1.Certificate",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "issuer", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "external_reference", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "issued_at", kind: "message", T: Timestamp },
  ],
);

