// @generated by protoc-gen-es v1.1.0
// @generated from file certificate/v1/certificate.proto (package certificate.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * METADATA 
 *
 * @generated from message certificate.v1.Certificate
 */
export declare class Certificate extends Message<Certificate> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: string issuer = 3;
   */
  issuer: string;

  /**
   * @generated from field: optional string external_reference = 4;
   */
  externalReference?: string;

  /**
   * @generated from field: google.protobuf.Timestamp issued_at = 5;
   */
  issuedAt?: Timestamp;

  constructor(data?: PartialMessage<Certificate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "certificate.v1.Certificate";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Certificate;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Certificate;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Certificate;

  static equals(a: Certificate | PlainMessage<Certificate> | undefined, b: Certificate | PlainMessage<Certificate> | undefined): boolean;
}

