// @generated by protoc-gen-es v1.1.0
// @generated from file trace/v1/trace.proto (package trace.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * METADATA 
 *
 * @generated from message trace.v1.Trace
 */
export const Trace = proto3.makeMessageType(
  "trace.v1.Trace",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(Trace_Type) },
    { no: 2, name: "departure", kind: "message", T: Trace_Location, opt: true },
    { no: 3, name: "destination", kind: "message", T: Trace_Location },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "co2e", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "footprint" },
    { no: 6, name: "co2o", kind: "scalar", T: 4 /* ScalarType.UINT64 */, oneof: "footprint" },
    { no: 7, name: "started_at", kind: "message", T: Timestamp },
    { no: 8, name: "duration", kind: "message", T: Duration },
  ],
);

/**
 * @generated from enum trace.v1.Trace.Type
 */
export const Trace_Type = proto3.makeEnum(
  "trace.v1.Trace.Type",
  [
    {no: 0, name: "TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "TYPE_AIR", localName: "AIR"},
    {no: 2, name: "TYPE_SEA", localName: "SEA"},
    {no: 3, name: "TYPE_LAND", localName: "LAND"},
  ],
);

/**
 * @generated from message trace.v1.Trace.Location
 */
export const Trace_Location = proto3.makeMessageType(
  "trace.v1.Trace.Location",
  () => [
    { no: 1, name: "place", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "lat", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "lng", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
  {localName: "Trace_Location"},
);

