// @generated by protoc-gen-es v1.1.0
// @generated from file transaction/v1/transaction.proto (package transaction.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message transaction.v1.Transaction
 */
export const Transaction = proto3.makeMessageType(
  "transaction.v1.Transaction",
  [],
);

