// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: wallet/v1/wallet.proto

package v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/orbyc/core/domain/wallet/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// WalletName is the fully-qualified name of the Wallet service.
	WalletName = "orbyc.wallet.Wallet"
)

// WalletClient is a client for the orbyc.wallet.Wallet service.
type WalletClient interface {
	GetAddress(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAddressResponse], error)
	CreateSignature(context.Context, *connect_go.Request[v1.CreateSignatureRequest]) (*connect_go.Response[v1.CreateSignatureResponse], error)
	CreateTransaction(context.Context, *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error)
}

// NewWalletClient constructs a client for the orbyc.wallet.Wallet service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWalletClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) WalletClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &walletClient{
		getAddress: connect_go.NewClient[emptypb.Empty, v1.GetAddressResponse](
			httpClient,
			baseURL+"/orbyc.wallet.Wallet/GetAddress",
			opts...,
		),
		createSignature: connect_go.NewClient[v1.CreateSignatureRequest, v1.CreateSignatureResponse](
			httpClient,
			baseURL+"/orbyc.wallet.Wallet/CreateSignature",
			opts...,
		),
		createTransaction: connect_go.NewClient[v1.CreateTransactionRequest, v1.CreateTransactionResponse](
			httpClient,
			baseURL+"/orbyc.wallet.Wallet/CreateTransaction",
			opts...,
		),
	}
}

// walletClient implements WalletClient.
type walletClient struct {
	getAddress        *connect_go.Client[emptypb.Empty, v1.GetAddressResponse]
	createSignature   *connect_go.Client[v1.CreateSignatureRequest, v1.CreateSignatureResponse]
	createTransaction *connect_go.Client[v1.CreateTransactionRequest, v1.CreateTransactionResponse]
}

// GetAddress calls orbyc.wallet.Wallet.GetAddress.
func (c *walletClient) GetAddress(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAddressResponse], error) {
	return c.getAddress.CallUnary(ctx, req)
}

// CreateSignature calls orbyc.wallet.Wallet.CreateSignature.
func (c *walletClient) CreateSignature(ctx context.Context, req *connect_go.Request[v1.CreateSignatureRequest]) (*connect_go.Response[v1.CreateSignatureResponse], error) {
	return c.createSignature.CallUnary(ctx, req)
}

// CreateTransaction calls orbyc.wallet.Wallet.CreateTransaction.
func (c *walletClient) CreateTransaction(ctx context.Context, req *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error) {
	return c.createTransaction.CallUnary(ctx, req)
}

// WalletHandler is an implementation of the orbyc.wallet.Wallet service.
type WalletHandler interface {
	GetAddress(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAddressResponse], error)
	CreateSignature(context.Context, *connect_go.Request[v1.CreateSignatureRequest]) (*connect_go.Response[v1.CreateSignatureResponse], error)
	CreateTransaction(context.Context, *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error)
}

// NewWalletHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWalletHandler(svc WalletHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/orbyc.wallet.Wallet/GetAddress", connect_go.NewUnaryHandler(
		"/orbyc.wallet.Wallet/GetAddress",
		svc.GetAddress,
		opts...,
	))
	mux.Handle("/orbyc.wallet.Wallet/CreateSignature", connect_go.NewUnaryHandler(
		"/orbyc.wallet.Wallet/CreateSignature",
		svc.CreateSignature,
		opts...,
	))
	mux.Handle("/orbyc.wallet.Wallet/CreateTransaction", connect_go.NewUnaryHandler(
		"/orbyc.wallet.Wallet/CreateTransaction",
		svc.CreateTransaction,
		opts...,
	))
	return "/orbyc.wallet.Wallet/", mux
}

// UnimplementedWalletHandler returns CodeUnimplemented from all methods.
type UnimplementedWalletHandler struct{}

func (UnimplementedWalletHandler) GetAddress(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.GetAddressResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("orbyc.wallet.Wallet.GetAddress is not implemented"))
}

func (UnimplementedWalletHandler) CreateSignature(context.Context, *connect_go.Request[v1.CreateSignatureRequest]) (*connect_go.Response[v1.CreateSignatureResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("orbyc.wallet.Wallet.CreateSignature is not implemented"))
}

func (UnimplementedWalletHandler) CreateTransaction(context.Context, *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("orbyc.wallet.Wallet.CreateTransaction is not implemented"))
}
